# Generated by Django 3.1.2 on 2020-11-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201107_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lasr_name',
            new_name='last_name',
        ),
    ]
