# Generated by Django 3.1.2 on 2020-12-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201209_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
